### PR TITLE
Create zaborona-proxy.pac

### PR DESCRIPTION
**Pull request by glopper**
Proxy auto-configuration file for firefox, to use with zaborona.help SOCKS5 proxy (socks.zaborona.help:1488).
As it uses DNS resolving, DNS server should be set to some external (non-ISP-provided) DNS service.

### CODE REVIEW

**Comment by zhovner** [comment]
Many IPS's like Kyivstar hijacks DNS responds from any DNS servers and redirects users to blocked page. So this solution will not work in most cases.

**Comment by soredake** [comment]
any progress on this?

**Comment by toxi22** [comment]
> any progress on this?

No progress yet

**Comment by toxi22** [comment]
> any progress on this?

The configuration has been updated. Please check how the sites work

**Pull request merged**
